#################################################################
#
# Foreman for Python
#
# Copyright (C) 2017 Satoshi Konno. All rights reserved.
#
# This is licensed under BSD-style license, see file COPYING.
#
##################################################################

FOREMAN_PRODUCT_NAME = "foreman"
FOREMAN_DEFAULT_SERVER_HOST = "localhost"
FOREMAN_DEFAULT_CARBON_PORT = 2003
FOREMAN_DEFAULT_HTTP_PORT = 8080
FOREMAN_HTTP_SERVER_FQL_PATH = "/fql"
FOREMAN_HTTP_SERVER_FQL_QUERY = "q"
FOREMAN_CONFIG_CATEGORY_KEY = "config"
FOREMAN_CONFIG_PRODUCT_KEY = "product"
FOREMAN_CONFIG_VERSION_KEY = "version"
FOREMAN_CONFIG_HOST_KEY = "host"
FOREMAN_CONFIG_CARBON_PORT_KEY = "carbon_port"
FOREMAN_CONFIG_HTTP_PORT_KEY = "http_port"
FOREMAN_ACTION_ENCODING_BASE64 = "base64"
FOREMAN_ACTION_LANGUAGE_PYTHON = "python"
FOREMAN_ACTION_LANGUAGE_LUA = "lua"
FOREMAN_ACTION_COLUMN_METHODS = "methods"
FOREMAN_ACTION_COLUMN_NAME = "name"
FOREMAN_ACTION_COLUMN_CODE = "code"
FOREMAN_ACTION_COLUMN_ENCODING = "encoding"
FOREMAN_ACTION_COLUMN_LANGUAGE = "language"
FOREMAN_ROUTE_COLUMN_ROUTES = "routes"
FOREMAN_ROUTE_COLUMN_NAME = "name"
FOREMAN_ROUTE_COLUMN_SOURCE = "src"
FOREMAN_ROUTE_COLUMN_DESTINATION = "dest"
FOREMAN_QUERY_INSERT_STRING = "INSERT"
FOREMAN_QUERY_SELECT_STRING = "SELECT"
FOREMAN_QUERY_DELETE_STRING = "DELETE"
FOREMAN_QUERY_TARGET_QOS = "QOS"
FOREMAN_QUERY_TARGET_CONFIG = "CONFIG"
FOREMAN_QUERY_TARGET_METRICS = "METRICS"
FOREMAN_QUERY_TARGET_REGISTER = "REGISTER"
FOREMAN_QUERY_TARGET_REGISTRY = "REGISTRY"
FOREMAN_QUERY_TARGET_ACTION = "ACTION"
FOREMAN_QUERY_TARGET_ROUTE = "ROUTE"
FOREMAN_QUERY_CONDITION_OPERATOR_LT = "<"
FOREMAN_QUERY_CONDITION_OPERATOR_LE = "<="
FOREMAN_QUERY_CONDITION_OPERATOR_GT = ">"
FOREMAN_QUERY_CONDITION_OPERATOR_GE = ">="
FOREMAN_QUERY_CONDITION_OPERATOR_EQ = "=="
FOREMAN_QUERY_CONDITION_OPERATOR_NEQ = "!="
FOREMAN_QUERY_COLUMN_NAME = "name"
FOREMAN_QUERY_COLUMN_TIMESTAMP = "ts"
FOREMAN_QUERY_COLUMN_VALUE = "value"
FOREMAN_QUERY_COLUMN_VERSION = "ver"
FOREMAN_GRAPHITE_RESPONSE_TARGET = "target"
FOREMAN_GRAPHITE_RESPONSE_DATAPOINTS = "datapoints"
