#################################################################
#
# Foreman for Python
#
# Copyright (C) 2017 Yahoo Japan Corporation. All rights reserved.
#
# This is licensed under BSD-style license, see file COPYING.
#
##################################################################

FOREMAN_PRODUCT_NAME = "foreman"
FOREMAN_DEFAULT_SERVER_HOST = "localhost"
FOREMAN_DEFAULT_CARBON_PORT = 2003
FOREMAN_DEFAULT_HTTP_PORT = 8188
FOREMAN_DEFAULT_RPC_PROTOCOL = "http"
FOREMAN_DEFAULT_LOG_FILE = "-"
FOREMAN_DEFAULT_LOG_LEVEL = "INFO"
FOREMAN_DEFAULT_METRICS_STORE = "empty"
FOREMAN_DEFAULT_BOOSTRAP_MODE = 0
FOREMAN_HTTP_REQUEST_FQL_PATH = "/fql"
FOREMAN_HTTP_REQUEST_FQL_QUERY_PARAM = "q"
FOREMAN_HTTP_REQUEST_FQL_RETRANSMISSION_PARAM = "r"
FOREMAN_CONFIG_CATEGORY_KEY = "config"
FOREMAN_CONFIG_PRODUCT_KEY = "product"
FOREMAN_CONFIG_VERSION_KEY = "version"
FOREMAN_CONFIG_HOST_KEY = "host"
FOREMAN_CONFIG_CARBON_PORT_KEY = "carbon_port"
FOREMAN_CONFIG_HTTP_PORT_KEY = "http_port"
FOREMAN_CONFIG_FQL_PATH_KEY = "fql_path"
FOREMAN_CONFIG_FQL_QUERY_KEY = "fql_query"
FOREMAN_CONFIG_LOG_FILE_KEY = "log_file"
FOREMAN_CONFIG_LOG_LEVEL_KEY = "log_level"
FOREMAN_CONFIG_BOOSTRAP_KEY = "boostrap"
FOREMAN_METRIC_STORE_EMPTY = "empty"
FOREMAN_METRIC_STORE_SQLITE = "sqlite"
FOREMAN_METRIC_STORE_TSMAP = "tsmap"
FOREMAN_METRIC_STORE_RINGMAP = "ringmap"
FOREMAN_ACTION_ENCODING_BASE64 = "base64"
FOREMAN_ACTION_LANGUAGE_PYTHON = "python"
FOREMAN_ACTION_LANGUAGE_LUA = "lua"
FOREMAN_ACTION_LANGUAGE_SYSTEM = "system"
FOREMAN_ACTION_COLUMN_METHODS = "methods"
FOREMAN_ACTION_COLUMN_NAME = "name"
FOREMAN_ACTION_COLUMN_CODE = "code"
FOREMAN_ACTION_COLUMN_ENCODING = "encoding"
FOREMAN_ACTION_COLUMN_LANGUAGE = "language"
FOREMAN_ROUTE_COLUMN_ROUTES = "routes"
FOREMAN_ROUTE_COLUMN_NAME = "name"
FOREMAN_ROUTE_COLUMN_SOURCE = "src"
FOREMAN_ROUTE_COLUMN_DESTINATION = "dest"
FOREMAN_QUERY_INSERT_STRING = "INSERT"
FOREMAN_QUERY_SELECT_STRING = "SELECT"
FOREMAN_QUERY_DELETE_STRING = "DELETE"
FOREMAN_QUERY_ANALYZE_STRING = "ANALYZE"
FOREMAN_QUERY_EXECUTE_STRING = "EXECUTE"
FOREMAN_QUERY_TARGET_QOS = "QOS"
FOREMAN_QUERY_TARGET_CONFIG = "CONFIG"
FOREMAN_QUERY_TARGET_METRICS = "METRICS"
FOREMAN_QUERY_TARGET_REGISTER = "REGISTER"
FOREMAN_QUERY_TARGET_REGISTRY = "REGISTRY"
FOREMAN_QUERY_TARGET_ACTION = "ACTION"
FOREMAN_QUERY_TARGET_ROUTE = "ROUTE"
FOREMAN_QUERY_TARGET_TYPE_NONE = 0
FOREMAN_QUERY_TARGET_TYPE_SHARED = 1
FOREMAN_QUERY_TARGET_TYPE_FEDERATED = 2
FOREMAN_QUERY_TARGET_TYPE_STANDALONE = 3
FOREMAN_QUERY_CONDITION_OPERATOR_LT = "<"
FOREMAN_QUERY_CONDITION_OPERATOR_LE = "<="
FOREMAN_QUERY_CONDITION_OPERATOR_GT = ">"
FOREMAN_QUERY_CONDITION_OPERATOR_GE = ">="
FOREMAN_QUERY_CONDITION_OPERATOR_EQ = "=="
FOREMAN_QUERY_CONDITION_OPERATOR_NEQ = "!="
FOREMAN_QUERY_COLUMN_ALL = "*"
FOREMAN_QUERY_COLUMN_NAME = "name"
FOREMAN_QUERY_COLUMN_TIMESTAMP = "ts"
FOREMAN_QUERY_COLUMN_VALUE = "value"
FOREMAN_QUERY_COLUMN_VERSION = "ver"
FOREMAN_GRAPHITE_RESPONSE_TARGET = "target"
FOREMAN_GRAPHITE_RESPONSE_DATAPOINTS = "datapoints"
FOREMAN_RPC_ERROR = "error"
FOREMAN_RPC_ERROR_CODE = "code"
FOREMAN_RPC_ERROR_MESSAGE = "message"
FOREMAN_RPC_ERROR_DETAIL = "detail"
FOREMAN_RPC_ERROR_DETAIL_CODE = "code"
FOREMAN_RPC_ERROR_DETAIL_MESSAGE = "message"
